### ISSUE TITLE
[BUG] Unexpected )

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/feathersui-openfl#17]
![image](https://user-images.githubusercontent.com/10191085/66711998-0e10b800-ed64-11e9-8b2e-ab54716fdbc2.png)

![image](https://user-images.githubusercontent.com/10191085/66711905-c0e01680-ed62-11e9-97f4-914f4eb01b2d.png)

### Fix Attempt

I tried debugging the FeathersEvent.hx file to fix the error, but can't see where the code is wrong or where it has an extra ')'. I'm new to Haxe. Also went to Haxe documentation and tried adding a return type of **FeathersEvent** to the ObjectPool instance callback param.

OpenFL works fine on VSCode without any FeathersUI code and all the dependencies are ok and up to date (lime, actuate, openfl, haxe, haxelib, feathersui, etc.).

### Note
I am aware this is an alpha state because another developer mentioned it.

**Comment by joshtynjala** [comment]
Do you have Haxe 4 installed?

**Comment by angelhdz** [comment]
> Do you have Haxe 4 installed?

👋Thanks for replying. 

Woops. That makes sense. Didn't check FeathersUI requirements. I'm starting with Haxe now only for Feathers.

Cheers!
