### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by manjav** [BowlerHatLLC/feathersui-openfl#22]
Hi
in components-explorer project when build android appears. (all haxelib plugins are up to date).
Thanks

arm-linux-androideabi-g++ -Iinclude --sysroot=C:\\_softwares\\android-ndk-r15c-windows-x86_64\\android-ndk-r15c/platforms/android-16/arch-arm -IC:\\_softwares\\android-ndk-r15c-windows-x86_64\\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -IC:\\_softwares\\android-ndk-r15c-windows-x86_64\\android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -DHXCPP_ARMV7 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -IC:/HaxeToolkit/haxe/lib/hxcpp/4,0,64/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -Wno-overflow -D_LINUX_STDDEF_H  -Wno-psabi -DHXCPP_CPP11 -DHXCPP_ARMV7 -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=16 -Wa,--noexecstack -O2 -DNDEBUG -c ... tags=[haxe,static]
 - src/__boot__.cpp
 - src/feathers/controls/ListView.cpp
 - src/openfl/display/GraphicsSolidFill.cpp  [haxe,release]
Error: ./src/feathers/controls/ListView.cpp: In member function 'virtual hx::Val feathers::controls::ListView_obj::__Field(const String&, hx::PropertyAccess)':      
./src/feathers/controls/ListView.cpp:928:91: error: operands to ?: have different types 'int' and 'Dynamic'
   if (HX_FIELD_EQ(inName,"selectedItem") ) { return hx::Val( inCallProp == hx::paccAlways ? get_selectedItem() : selectedItem ); }

**Comment by joshtynjala** [comment]
I was able to reproduce and fix the issue. Thank you!
