### ISSUE TITLE
Example of CustomItemRenderer

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/feathersui-openfl#23]
I can't find any documentation or example to how to create custom item renderer of ListView.
@joshtynjala can you explain me how to create and use a custom itemrenderer? I want to create an item renderer to show image, with passed url like this:

`this.dataProvider.add({url:"....."});`

**Comment by joshtynjala** [comment]
You can provide a custom item renderer by setting the [`itemRendererRecycler`](https://api.feathersui.com/unstable/feathers/controls/ListView.html#itemRendererRecycler) property.

```hx
list.itemRendererRecycler = DisplayObjectRecycler.withClass(CustomItemRenderer);
```

If your custom item renderer implements the [`IDataRenderer`](https://api.feathersui.com/unstable/feathers/controls/dataRenderers/IDataRenderer.html) interface, the `data` property will be set to an item from the ListView's data provider. You can interpret that item in any way that you'd like, inside an override of `update()`.

However, [`DisplayObjectRecycler`](https://api.feathersui.com/unstable/feathers/utils/DisplayObjectRecycler.html) makes it possible to skip implementing `IDataRenderer`, if you'd prefer. You can optionally provide `update` and `reset` methods to that interpret the data.

Here's an example that creates a LayoutGroup with a Label and an AssetLoader:

```hx
var recycler = DisplayObjectRecycler.withFunction(() ->
{
	var itemRenderer = new LayoutGroup();
	var label = new Label();
	label.name = "label";
	itemRenderer.addChild(label);
	var loader = new AssetLoader();
	loader.name = "loader";
	itemRenderer.addChild(loader);
	return itemRenderer;
});

recycler.update = (itemRenderer, state) ->
{
	var label = cast(itemRenderer.getChildByName("label"), Label);
	var loader = cast(itemRenderer.getChildByName("loader"), AssetLoader);

	label.text = state.text;
	loader.source = state.data.url;
});

recycler.reset = (itemRenderer, state) ->
{
	var label = cast(itemRenderer.getChildByName("label"), Label);
	var loader = cast(itemRenderer.getChildByName("loader"), AssetLoader);

	label.text = "";
	loader.source = null;
});

list.itemRendererRecycler = recycler;
```

(Note: I haven't tried running that code, so it may need some minor tweaks to work properly)

I'm working on the documentation this month, and I'll try to go into more detail on item renderers. In the meantime, feel free to ask if anything is confusing.

**Comment by varadig** [comment]
Thank You @joshtynjala!
