### ISSUE TITLE
Combobox has strange look

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathersui-openfl#24]
Before updating from github, it was ok :)

![image](https://user-images.githubusercontent.com/1607138/73467283-cb630200-438b-11ea-88cf-3b16f4485675.png)

**Comment by joshtynjala** [comment]
Yeah, the arrow icon seems to have disappeared for some reason. I'll take a look.

**Comment by joshtynjala** [comment]
Sorry about that! I made a simple copy-paste mistake.
