### ISSUE TITLE
How to specify max visible items in combobox list?

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathersui-openfl#28]
Sorry, didn't find in API docs

**Comment by CrazyFlasher** [comment]
Currently I found possibility to specifiy list view height by getting reference to ListView via ComboBox listViewFactory

**Comment by joshtynjala** [comment]
Yeah, you can either specify the height like that, or you can set the [`requestedRowCount`](https://api.feathersui.com/current/feathers/layout/VerticalListFixedRowLayout.html#requestedRowCount) property on [`VerticalListFixedRowLayout`](https://api.feathersui.com/current/feathers/layout/VerticalListFixedRowLayout.html).
