### ISSUE TITLE
TextArea doesn't display text

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathersui-openfl#29]
Sorry, may be its incomplete yet

**Comment by joshtynjala** [comment]
It should be working correctly. Can you post some example code?

**Comment by CrazyFlasher** [comment]
You can just add `this.textArea.text = "My cool text";` to `TextAreaScreen` sample and TextArea remain empty
![image](https://user-images.githubusercontent.com/1607138/75164293-48825c80-5729-11ea-95f7-2dc8641724ad.png)

**Comment by joshtynjala** [comment]
Okay, thanks. I may have forgotten to pass the text to the inner TextFieldViewPort when it is set programmatically. I think I've only tested by typing the text at runtime.
