### ISSUE TITLE
a couple minor nitpicks

### ISSUE THREAD

**Issue by nadako** [BowlerHatLLC/feathersui-openfl#3]
Hey! Thanks for open sourcing this project and I gotta say the code looks very nice and clean.

I'm just creating this issue to mention a couple things that you might not know about yet, for example here:

https://github.com/BowlerHatLLC/feathersui-openfl/blob/9f071e1e5e8b3c13f0f9e92d36132bdf32003ca3/src/feathers/layout/VerticalListFixedRowLayout.hx#L79-L88

First, you can directly do `for (item in items)`, that will generate pretty much the same code.

Second, the `Std.is(...)` followed by a safe-`cast` will actually do the type-check twice, so probably using `Std.downcast` is better in this case.

**Comment by joshtynjala** [comment]
Is `for (item in items)` guaranteed to be in order? Even if that's the case, I'm somewhat wary because it's not always true in other languages. I'd rather have code that doesn't require remembering how something behaves.

> so probably using Std.downcast is better in this case.

Just to be sure that I fully understand, can you post an actual code example of the change that you're suggesting?

**Comment by nadako** [comment]
> Is `for (item in items)` guaranteed to be in order? Even if that's the case, I'm somewhat wary because it's not always true in other languages. I'd rather have code that doesn't require remembering how something behaves.

Ordering depends on a collection/iterator, and since Array is an ordered collection, of course it's guaranteed to be in order. I think that's the same for every language that supports "declarative" `for`.

> can you post an actual code example of the change that you're suggesting

Something like:
```haxe
var layoutObject = Std.downcast(item, ILayoutObject);
if (layoutObject != null && !layoutObject.includeInLayout) {
    continue;
}
```

**Comment by Gama11** [comment]
>Is `for (item in items)` guaranteed to be in order? Even if that's the case, I'm somewhat wary because it's not always true in other languages.

Huh? In what language is this not the case?

**Comment by back2dos** [comment]
JS/AS would come to my mind, because there it means key iteration. But `for/of` (which is the actual counterpart to Haxe's `for/in`) is indeed well defined for arrays.

**Comment by nadako** [comment]
> JS/AS would come to my mind, because there it means key iteration.

AFAIK  the order of "keys" for Array is still defined there.

**Comment by back2dos** [comment]
> AFAIK the order of "keys" for Array is still defined there.

Sorry to disappoint, but I have bad news for you:

> There is no guarantee that `for...in` will return the indexes in any particular order.  - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in)

IIRC AS2 would rather consistently give the array keys to you in reverse order ¯\\\_(ツ)\_/¯

**Comment by nadako** [comment]
> IIRC AS2 would rather consistently give the array keys to you in reverse order ¯\_(ツ)_/¯

LOL, but oh well, as you already mentioned, Haxe `for` is different and more properly "maps" to ES6 for/of loops, or e.g. C# for each, so one should not be afraid to use it and it has better expressiveness.

**Comment by joshtynjala** [comment]
@nadako Unfortunately, this code that you suggested does not work:

```hx
var layoutObject = Std.downcast(item, ILayoutObject);
if (layoutObject != null && !layoutObject.includeInLayout) {
    continue;
}
```

Compiler error:

> Constraint check failure for downcast. feathers.layout.ILayoutObject should be openfl.display.DisplayObject
