### ISSUE TITLE
styleProvider.applyStyles called twice

### ISSUE THREAD

**Issue by brighttank** [BowlerHatLLC/feathersui-openfl#37]
The applyStyles method of the FeathersControl.styleProvider is called twice.

```
class HomeView extends LayoutGroup {
    override private function initialize() {
        super.initialize();

        var button = new Button();
        button.styleProvider = new FunctionStyleProvider((target:Button) -> {
            trace('I WILL GET CALLED TWICE');
            target.backgroundSkin = new RectangleSkin();
        });

        addChild(button);
    }
}
```

The issues seems to be in FeathersControl.applyStyles:

```
// if there was a different style provider previously, clear old styles
this.clearStyles();

```

Despite the comment it clears styles regardless of whether the styleProvider has changed.

The function used to apply the styles could be quite resource intensive so it would be a good idea to make sure it's not called unnecessarily.

**Comment by joshtynjala** [comment]
This issue is caused by openfl/openfl#2177

**Comment by brighttank** [comment]
It also occurs if you set the style provider after the component has been initialized. The setter method will call applyStyles because the control is initialized and then applyStyles will get called again on update.

Either way, wouldn't the fix be to set a flag around the call as the comment above the clearStyles() call suggests?

**Comment by joshtynjala** [comment]
> The setter method will call applyStyles because the control is initialized and then applyStyles will get called again on update.

Which line exactly does applyStyles() get called the second time?

**Comment by brighttank** [comment]
From FeathersControl.hx

```
	private function set_styleProvider(value:IStyleProvider):IStyleProvider {
		if (this._customStyleProvider == value) {
			return this._customStyleProvider;
		}
		this._customStyleProvider = value;
		if (this.initialized) {
			// ignore if we're not initialized yet because it will be handled
			// later. otherwise, apply the new styles immediately.
			this.applyStyles();
		}
		this.setInvalid(InvalidationFlag.STYLES);
		return this._customStyleProvider;
	}

```

If this.initialized is true then this.applyStyles() will get called. Then the invalidation flag is set which results in it getting called again.

**Comment by joshtynjala** [comment]
How does setInvalid(InvalidationFlag.STYLES) cause applyStyles() to get called again?

**Comment by brighttank** [comment]
You're right. I just stepped through the code again. The second call is actually because of the duplicate added to stage event. I'd incorrectly assumed the invalidation was going to applyStyles again.

I still think it would be useful to not clearStyles() if it's not necessary. I'm actually porting a skin class from the Starling version which already guards against duplicate calls. This meant that the styles were getting cleared the second time through and then my skin wasn't reapplying them again.

**Comment by joshtynjala** [comment]
I added a guard for the duplicate Event.ADDED_TO_STAGE event.

I need to think some more about adding a guard for clearStyles(). If I were to add something, it would only prevent clearStyles() from being called if _currentStyleProvider were null. I suspect that you are expecting some additional conditions for clearStyles() to be skipped, but any other reason for skipping it could cause some old styles to be left behind that shouldn't be.
