### ISSUE TITLE
VerticalListFixedRowLayout incorrectly calculates getVisibleIndices when _paddingTop != 0

### ISSUE THREAD

**Issue by brighttank** [BowlerHatLLC/feathersui-openfl#42]
If I used the VerticalListLayout I can set the paddingTop and things work as expected - ie. the items fill up the screen as I scroll up past the paddingTop. But with the fixed layout it doesn't work.

Issue seems to be in getVisibleIndices:
```
		var startIndex = 0;
		var endIndex = 0;
		if (itemHeight > 0.0) {
			startIndex = Math.floor(this._scrollY / itemHeight);
			if (startIndex < 0) {
				startIndex = 0;
			}
```

startIndex should factor in the _paddingTop no?

**Comment by joshtynjala** [comment]
Thanks!
