### ISSUE TITLE
[iOS] Chinese, Japanese, Korean characters in Label don’t render

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathersui-openfl#48]
Hi.
I guess this is OpenFL related.
May be you have an idea? :)

OpenFL 9.0.2
Lime: 7.8.0
Haxe: 4.1.4

UPD: They appear only if I add font files that support this characters to project assets. But how to use device fonts instead?

**Comment by joshtynjala** [comment]
> UPD: They appear only if I add font files that support this characters to project assets. But how to use device fonts instead?

OpenFL must not be choosing a good default font that supports these languages.

openfl/openfl@8e3f356ebfe388318a9cfe04d573e04e8828a3c6 recently resolved an issue where fonts like _sans didn't work for English either (issue openfl/openfl#2316). The solution for other languages is probably related.

**Comment by CrazyFlasher** [comment]
assigning font name as "_sans", "_serif" or "_typewriter" doesn't fix the issue  :(

**Comment by joshtynjala** [comment]
Hopefully, OpenFL can be updated to choose the correct font that supports all languages.
