### ISSUE TITLE
Using prompt property seems to freeze the TextInput component on HTML5

### ISSUE THREAD

**Issue by dimpletherat** [BowlerHatLLC/feathersui-openfl#53]
tested with Feathersui 1.0.0-beta.2, OpenFL 9.0.2 on HTML5 target, any renderer

[feathersui-textinput-prompt.zip](https://github.com/BowlerHatLLC/feathersui-openfl/files/5711870/feathersui-textinput-prompt.zip)

**Comment by joshtynjala** [comment]
Thank you! I'll take a look as soon as I can. With the holidays, it may not be until January.
