### ISSUE TITLE
KeyboardEvent.KEY_DOWN event has not been received in component when I pressed arrow keys

### ISSUE THREAD

**Issue by piotrzarzycki21** [BowlerHatLLC/feathersui-openfl#54]
When I register on event using KeyboardEvent.KEY_DOWN my event handler has not been called when I press on keyboard navigation arrows.

More information here -> https://github.com/prominic/Moonshine-IDE/issues/771#issuecomment-762415110

**Comment by joshtynjala** [comment]
b903c9926d6a4d609e6c219f1c80e8d760b5cfe2
