### ISSUE TITLE
PageNavigator doesn't update PageIndicator when dataProvider length changes

### ISSUE THREAD

**Issue by brighttank** [BowlerHatLLC/feathersui-openfl#58]
If you add items the the PageNavigator.dataProvider after the component has been added_to_stage the PageIndicator doesn't get updated to show the new number of pages.

Seems the pageNavigator_dataProvider_addItemHandler and pageNavigator_dataProvider_removeItemHandler functions should setInvalid(DATA) to make sure the PageIndicator gets updated on the next update cycle.

**Comment by joshtynjala** [comment]
Fixed. Thank you!
