### ISSUE TITLE
ResponsiveGridLayout constructor not using columnCount property correctly

### ISSUE THREAD

**Issue by jawchewa** [BowlerHatLLC/feathersui-openfl#61]
The ResponsiveGridLayout API documentation suggests that you should be able to use the first argument to set the column count.
https://api.feathersui.com/v1.0.0-beta.2/feathers/layout/ResponsiveGridLayout.html

But it looks like the constructor hard codes it to 12. This should probably be updated so it actually uses the columnCount parameter, instead of hard coding it. This is just a minor bug, and there is an easy workaround, because you can just set the columnCount property after instantiating the layout.
https://github.com/BowlerHatLLC/feathersui-openfl/blob/v1.0.0-beta.2/src/feathers/layout/ResponsiveGridLayout.hx
Relevant code:
```
	public function new(columnCount:Int = 12, sm:Float = 576.0, md:Float = 768.0, lg:Float = 992.0, xl:Float = 1200.0) {
		super();
		this._columnCount = 12;
		this._sm = sm;
		this._md = md;
		this._lg = lg;
		this._xl = xl;
	}```

**Comment by joshtynjala** [comment]
Already fixed in commit 66c29bd725925a089537f7bc73e8f918af60159e. The fix will be included in beta.3.
